def generate_summary():
    """
    Mock investigation summary.
    Later this will be generated by deterministic Python logic.
    """

    return {
        "summary": [
            "Multiple failed PIX transactions were detected.",
            "Elevated error rate was identified.",
            "The payment provider status is degraded.",
            "Three similar incidents were found."
        ],
        "recommendation": "Create an incident ticket."
    }